AWSTemplateFormatVersion: 2010-09-09

Parameters:
  BotName:
    Type: String
    Default: "SampleBot"

Resources:
  # 1. IAM Role
  BotRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lexv2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: LexRuntimeRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "polly:SynthesizeSpeech"
                  - "comprehend:DetectSentiment"
                Resource: "*"

  # 2. Lex Bot
  SampleBot:
    Type: AWS::Lex::Bot
    Properties:
      Name: !Ref BotName
      RoleArn: !GetAtt BotRole.Arn
      DataPrivacy:
        ChildDirected: false
      IdleSessionTTLInSeconds: 300
      Description: "Bot with Fallback and SampleDemo intents"
      AutoBuildBotLocales: false
      BotLocales:
        - LocaleId: "ja_JP"
          Description: "Japanese locale"
          NluConfidenceThreshold: 0.40
          Intents:
            - Name: "FallbackIntent"
              Description: "Default intent when no other intent matches"
              ParentIntentSignature: "AMAZON.FallbackIntent"
              FulfillmentCodeHook:
                Enabled: false
              DialogCodeHook:
                Enabled: false
            - Name: "SampleDemoIntent"
              Description: "Sample demo intent"
              SampleUtterances:
                - Utterance: "サンプルほげほげ"
              DialogCodeHook:
                Enabled: true

  # Version
  SampleBotVersion:
    Type: AWS::Lex::BotVersion
    Properties:
      BotId: !Ref SampleBot
      BotVersionLocaleSpecification:
        - LocaleId: ja_JP
          BotVersionLocaleDetails:
            SourceBotVersion: DRAFT

  # Alias
  BotAlias:
    Type: AWS::Lex::BotAlias
    Properties:
      BotId: !Ref SampleBot
      BotAliasName: "SampleBotAlias"
      BotVersion: !GetAtt SampleBotVersion.BotVersion
      SentimentAnalysisSettings:
        DetectSentiment: false
